# Generated by Django 3.2 on 2024-01-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('startprice', models.FloatField()),
                ('currentprice', models.FloatField()),
                ('end_date', models.DateField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('birth_date', models.DateField(max_length=30, null=True)),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
